/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CarResponse {
  id?: number;
  make?: string;
  model?: string;
  year?: number;
  price_per_day?: number;
  type?: string;
  imageUrl?: string;
}
