/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CarRequest {
  /**
   * @minLength 2
   * @maxLength 100
   */
  make: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  model: string;
  year: number;
  price_per_day: number;
  type: string;
  imageUrl?: string;
}
