/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CarResponse } from './carResponse';

export interface CartItemResponse {
  cartItemId?: number;
  car?: CarResponse;
  days?: number;
  dailyRate?: number;
  subtotal?: number;
}
