/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from './userResponse';
import type { CartItemResponse } from './cartItemResponse';

export interface OrderResponse {
  user?: UserResponse;
  total?: number;
  status?: string;
  orderItems?: CartItemResponse[];
}
