/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserRequestRole } from './userRequestRole';

export interface UserRequest {
  /**
   * @minLength 2
   * @maxLength 100
   */
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  created_at?: string;
  role?: UserRequestRole;
  /**
   * @minLength 2
   * @maxLength 100
   */
  user_name: string;
}
