/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserResponse {
  userName?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  password?: string;
  created_at?: string;
  userId?: number;
  role?: string;
  user_name?: string;
}
