/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserRequestRole = typeof UserRequestRole[keyof typeof UserRequestRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRequestRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
